In [1]:
import numpy as np

def prob_1D_from_u_1D(u,PE,perPE):
    pstart=np.zeros(PE)
    pend=np.zeros(PE)
    for pe in range(PE-1):
        pstart[pe+1]=u[(pe+1)*perPE]
        pend[pe]=u[(pe+1)*perPE-1]
        #Periodic Boundary points
    pstart[0]=u[0*perPE +1]
    pend[PE-1]=u[(PE)*perPE-1-1]
    
    return pstart,pend

def prob_2D_from_init_c(lis,init_c,PE,perPE,delay_max):
    L=delay_max
    ps=[]
    pe=[]
    pst_1d,pen_1d=prob_1D_from_u_1D(init_c,PE,perPE)
    ps.append(pst_1d)
    pe.append(pen_1d)
    for h in range(L-2):
        pst_1d,pen_1d=prob_1D_from_u_1D(lis[h],PE,perPE)
        ps.append(pst_1d)
        pe.append(pen_1d)

    prob_Start=np.stack(ps)
    prob_End=np.stack(pe)
    return prob_Start,prob_End

In [3]:
prob_1D_from_u_1D(np.arange(256),4,64)

(array([  1.,  64., 128., 192.]), array([ 63., 127., 191., 254.]))

In [ ]:
#Given 2D array containing 

In [2]:
def prob_2D_from_arr_2D(arr2D,PE,perPE,m):
    # m = L-1 steps
    if (m!=arr2D.shape[0]):
        print('ERROR : Shapes not compatible')
        return
    prob_S_list,prob_E_list=[],[]
    for i in range(m):
        ps,pe=prob_1D_from_u_1D(arr2D[i],PE,perPE)
        prob_S_list.append(ps)
        prob_E_list.append(pe)
    prob_2D_S_arr=np.stack(prob_S_list)
    prob_2D_E_arr=np.stack(prob_E_list)
    return prob_2D_S_arr,prob_2D_E_arr
        

In [10]:
prob_2D_from_arr_2D(np.zeros((2,3)),4,64,2)

Hello
Hello


In [4]:
x=np.arange(256)
x_2d=np.tile(x, (5, 1))
x_2d


array([[  0,   1,   2, ..., 253, 254, 255],
       [  0,   1,   2, ..., 253, 254, 255],
       [  0,   1,   2, ..., 253, 254, 255],
       [  0,   1,   2, ..., 253, 254, 255],
       [  0,   1,   2, ..., 253, 254, 255]])

In [5]:
prob_1D_from_u_1D(x,4,64)

(array([  1.,  64., 128., 192.]), array([ 63., 127., 191., 254.]))

In [7]:
p1,p2=prob_2D_from_arr_2D(x_2d,4,64,5)

In [9]:
p2

array([[ 63., 127., 191., 254.],
       [ 63., 127., 191., 254.],
       [ 63., 127., 191., 254.],
       [ 63., 127., 191., 254.],
       [ 63., 127., 191., 254.]])

In [39]:
y2[:,1:]

array([[[ 63., 127., 191., 254.]],

       [[ 63., 127., 191., 254.]],

       [[ 63., 127., 191., 254.]],

       [[ 63., 127., 191., 254.]],

       [[ 63., 127., 191., 254.]]])

In [32]:
a,b=[],[]

In [33]:
a

[]

In [34]:
b

[]